services:
  output-db:
    container_name: output-db
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pyspark-notebook:
    container_name: pyspark-notebook
    # profiles: 
    #   - notebook
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
  metabase:
    # profiles: 
    #   - visualization
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5555
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    # profiles: 
    #   - visualization
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
      PGPORT: 5555
    volumes:
      - metabase_pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  metabase_pgdata: