services:
  output-db:
    container_name: output-db
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pyspark-notebook:
    container_name: pyspark-notebook
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      
volumes:
  pgdata: