services:
  spark-master:
    container_name: da-spark-master
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - spark-logs:/opt/spark/spark-events
      - storage:/opt/spark/storage
    env_file:
      - spark_config/.env.spark
    ports:
      - '9090:8080'
      - '7077:7077'


  spark-history-server:
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - spark_config/.env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
      - storage:/opt/spark/storage
    ports:
      - '18080:18080'

  spark-worker-1:
    container_name: da-spark-worker-1
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - spark_config/.env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
      - storage:/opt/spark/storage
  
  spark-worker-2:
    container_name: da-spark-worker-2
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - spark_config/.env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
      - storage:/opt/spark/storage


  scheduler:
    volumes:
      - ../include:/usr/local/airflow/include
      - ../dags:/usr/local/airflow/dags
      - storage:/usr/local/airflow/storage:rw

  api-server:
    volumes:
      - ../include:/usr/local/airflow/include
      - ../dags:/usr/local/airflow/dags
      - storage:/usr/local/airflow/storage:rw
  
  dag-processor:
    volumes:
      - ../include:/usr/local/airflow/include
      - ../dags:/usr/local/airflow/dags
      - storage:/usr/local/airflow/storage:rw

volumes:
  storage:
  spark-logs:
